### ISSUE TITLE
Firefox compatibility

### ISSUE THREAD

**Issue by JLeFevre559** [JLeFevre559/CS350-Clipboard#36]
Firefox users can't see tasks on the calendar, and the date fields for editing a task do not auto-populate.

**Comment by alexhart00** [comment]
The calendar now displays the tasks with the proper popup information in Firefox.

**Comment by JLeFevre559** [comment]
The date fields for editing a task auto-populate on the latest version of firefox, this is a version specific issue. I can't reproduce this issue at home.
