### ISSUE TITLE
Alt Profile Picture Doesn't Always Show Up

### ISSUE THREAD

**Issue by alexhart00** [JLeFevre559/CS350-Clipboard#7]
For running locally (haven't checked the live deployment) on the profile.html when there isn't a profile picture the default of noProfilePicturePic.png from the static image folder should be loaded, in the script for the HTML the image will sometimes not load and display the alt text "ProfilePicture", but sometimes does, if you refresh the page about a dozen times you will see what I mean, probably related to server-related issues causing intermittent problems with resource loading. NOT A HIGH PRIORITY ISSUE.

**Comment by JLeFevre559** [comment]
We have switched to using a different implementation which does not have this issue.
